(function () {
  "use strict";

  const { kindForPath, kindForUrl } = globalThis.YouTubeContentFilterRules;
  const HIDDEN = "data-youtube-content-filter-hidden";
  const CARD = [
    "ytd-rich-item-renderer", "ytd-video-renderer", "ytd-grid-video-renderer",
    "ytd-compact-video-renderer", "ytd-playlist-video-renderer",
    "ytd-reel-item-renderer", "ytd-rich-grid-slim-media",
    "yt-lockup-view-model", "ytm-video-with-context-renderer",
    "ytm-compact-video-renderer", "ytm-shorts-lockup-view-model"
  ].join(",");
  const NAV = [
    "ytd-guide-entry-renderer", "ytd-mini-guide-entry-renderer",
    "ytd-guide-collapsible-section-entry-renderer", "ytd-pivot-bar-item-renderer",
    "ytm-pivot-bar-item-renderer", "ytm-guide-entry-renderer"
  ].join(",");
  const SHELF = [
    "ytd-rich-shelf-renderer", "ytd-shelf-renderer",
    "ytd-reel-shelf-renderer", "ytd-shorts-shelf-renderer",
    "ytm-reel-shelf-renderer"
  ].join(",");
  const GAME_METADATA = [
    "ytd-rich-metadata-renderer", "ytd-metadata-row-renderer",
    "ytd-game-info-renderer", "ytd-game-details-renderer",
    "ytd-game-card-renderer"
  ].join(",");
  const GUIDE_SECTION = "ytd-guide-section-renderer, ytm-guide-section-renderer";
  const KNOWN = [
    "ytd-reel-shelf-renderer", "ytd-shorts-shelf-renderer",
    "ytd-reel-item-renderer", "ytd-rich-grid-slim-media",
    "ytd-rich-shelf-renderer[is-shorts]",
    "ytd-rich-shelf-renderer[is-mini-game-card-shelf]",
    "ytd-mini-game-card-renderer", "ytd-game-card-renderer",
    "ytm-reel-shelf-renderer", "ytm-shorts-lockup-view-model"
  ].join(",");

  let scanTimer = 0;
  let fullScanPending = false;
  const pendingRoots = new Set();

  function hide(element) {
    if (!element || element.hasAttribute(HIDDEN)) return;
    element.setAttribute(HIDDEN, "");
  }

  function hideShelf(shelf) {
    // A rich section normally wraps exactly one shelf and owns its spacing.
    const section = shelf.closest("ytd-rich-section-renderer");
    if (section && section.querySelectorAll(SHELF).length === 1) hide(section);
    else hide(shelf);
  }

  function headingOf(shelf) {
    const heading = shelf.querySelector(
      ":scope > #header #title, :scope > #header #title-text, " +
      ":scope > #header h2, :scope > #title, :scope > #title-text, " +
      ":scope > h2, #header #title, #header h2"
    );
    return heading ? heading.textContent.trim().replace(/\s+/g, " ").toLowerCase() : "";
  }

  function isGameMetadata(element) {
    const text = element.textContent.trim().replace(/\s+/g, " ").toLowerCase();
    if (element.matches("ytd-game-info-renderer, ytd-game-details-renderer, ytd-game-card-renderer")) {
      return true;
    }
    if (/auto-generated by youtube/i.test(text) || /^game\s*:/i.test(text)) return true;
    return Array.from(element.querySelectorAll("a[href]")).some(
      (link) => kindForUrl(link.getAttribute("href"), location.href) === "gaming"
    );
  }

  function isShortsNav(nav) {
    const links = Array.from(nav.querySelectorAll("a[href]"));
    if (links.length) {
      return links.some((link) => kindForUrl(link.getAttribute("href"), location.href) === "shorts");
    }

    // The compact navigation can render a button before YouTube attaches its
    // destination. Only use its label when it has no other link to protect
    // ordinary navigation entries whose names happen to be "Shorts".
    const labels = [
      nav.getAttribute("aria-label"), nav.getAttribute("title"),
      nav.querySelector("[aria-label], [title]")?.getAttribute("aria-label"),
      nav.querySelector("[aria-label], [title]")?.getAttribute("title"),
      nav.textContent
    ];
    return labels.some((label) => label?.trim().toLowerCase() === "shorts");
  }

  function isMoreFromYouTube(section) {
    const heading = section.querySelector(
      "#guide-section-title, #section-title, :scope > h2, :scope > h3, " +
      ":scope > #header h2, :scope > #header h3"
    );
    return heading?.textContent.trim().replace(/\s+/g, " ").toLowerCase() === "more from youtube";
  }

  function hideLinkTarget(link, kind) {
    const nav = link.closest(NAV);
    if (nav) {
      hide(nav);
      return;
    }

    if (kind === "gaming") {
      const metadata = link.closest(GAME_METADATA);
      if (metadata) {
        hide(metadata);
        return;
      }
      // Game pages can be presented as cards. A video card may merely have
      // game metadata inside it, so never remove one for a Gaming link.
      const card = link.closest(CARD);
      if (card && !card.querySelector('a[href*="/watch?"], a[href*="/live/"]')) {
        hide(card);
      } else {
        hide(link);
      }
      return;
    }

    const shelf = link.closest(SHELF);
    if (shelf && headingOf(shelf) === kind) {
      hideShelf(shelf);
      return;
    }
    hide(link.closest(CARD) || link);
  }

  function forEachMatch(root, selector, callback) {
    if (root.matches(selector)) callback(root);
    for (const element of root.querySelectorAll(selector)) callback(element);
  }

  function scan(root) {
    // Only reconsider markers in the changed area. The DOM itself owns them,
    // so removed YouTube nodes cannot stay alive through an extension Set.
    forEachMatch(root, `[${HIDDEN}]`, (element) => element.removeAttribute(HIDDEN));

    forEachMatch(root, KNOWN, (element) => {
      const shelf = element.closest(SHELF);
      if (shelf && (element === shelf || element.matches("ytd-reel-item-renderer, ytd-rich-grid-slim-media"))) {
        // A single Shorts card should not erase an unrelated mixed shelf.
        if (element === shelf) hideShelf(shelf);
        else hide(element);
      } else {
        hide(element);
      }
    });

    forEachMatch(root, NAV, (nav) => {
      if (isShortsNav(nav)) hide(nav);
    });

    forEachMatch(root, GUIDE_SECTION, (section) => {
      if (isMoreFromYouTube(section)) hide(section);
    });

    forEachMatch(root, SHELF, (shelf) => {
      const heading = headingOf(shelf);
      if (heading === "shorts" || heading === "playables" || heading === "top live games") {
        hideShelf(shelf);
      }
    });

    forEachMatch(root, GAME_METADATA, (element) => {
      if (isGameMetadata(element)) hide(element);
    });

    forEachMatch(root, "a[href]", (link) => {
      const kind = kindForUrl(link.getAttribute("href"), location.href);
      if (kind) hideLinkTarget(link, kind);
    });
  }

  function guardLocation() {
    if (!kindForPath(location.pathname)) return false;
    location.replace(location.origin + "/");
    return true;
  }

  function scheduleScan() {
    if (!scanTimer) scanTimer = setTimeout(flushScans, 16);
  }

  function scheduleFullScan() {
    fullScanPending = true;
    pendingRoots.clear();
    scheduleScan();
  }

  function queueRoot(root) {
    if (!root || fullScanPending) return;
    pendingRoots.add(root);
    scheduleScan();
  }

  function scopeFor(node) {
    const element = node instanceof Element ? node : node.parentElement;
    if (!element) return null;
    // A rich section may be hidden on behalf of its only shelf. Rechecking
    // that section also handles shelves added or removed within it.
    return element.closest("ytd-rich-section-renderer") ||
      element.closest(`${NAV}, ${GUIDE_SECTION}, ${SHELF}, ${CARD}, ${GAME_METADATA}`);
  }

  function collectMutations(mutations) {
    for (const mutation of mutations) {
      const scope = scopeFor(mutation.target);
      if (scope) queueRoot(scope);
      else if (mutation.type === "attributes" && mutation.target instanceof Element) {
        queueRoot(mutation.target);
      }
      if (!scope && mutation.type === "childList") {
        for (const node of mutation.addedNodes) {
          if (node instanceof Element) queueRoot(node);
        }
      }
    }
  }

  function flushScans() {
    scanTimer = 0;
    if (guardLocation()) {
      fullScanPending = false;
      pendingRoots.clear();
      return;
    }
    if (fullScanPending) {
      fullScanPending = false;
      pendingRoots.clear();
      if (document.documentElement) scan(document.documentElement);
      return;
    }
    const roots = Array.from(pendingRoots);
    pendingRoots.clear();
    for (const root of roots) {
      if (root.isConnected) scan(root);
    }
  }

  function blockClick(event) {
    const link = event.target instanceof Element && event.target.closest("a[href]");
    if (!link || !kindForUrl(link.getAttribute("href"), location.href)) return;
    event.preventDefault();
    event.stopImmediatePropagation();
    location.replace(location.origin + "/");
  }

  if (guardLocation()) return;

  // Capture before YouTube's own single-page navigation handler.
  document.addEventListener("click", blockClick, true);
  document.addEventListener("auxclick", blockClick, true);
  document.addEventListener("yt-navigate-start", guardLocation, true);
  document.addEventListener("yt-navigate-finish", scheduleFullScan, true);
  window.addEventListener("popstate", guardLocation, true);

  new MutationObserver(collectMutations).observe(document, {
    childList: true,
    subtree: true,
    characterData: true,
    attributes: true,
    attributeFilter: ["href", "title", "aria-label", "is-shorts", "is-mini-game-card-shelf"]
  });
  scheduleFullScan();
})();
